# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f0479d2b1167b1b6c9fcf27ae9bd05c26a82b37d7a550f6d69d4a9a30a6c14b225791114bb56f831a00bc2de69c593a45c49b75aead575d91fa881e69f9efab

test:
  secret_key_base: cd1b8d288e9d41c4d9e887b2f4413a491bf21c22afa896e903db32a247229ce5f62c975acfe931137e34c2ee7dc7a32fa6822eaf2dc4e40a47aea05a7363de58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
